name: CI Piplines for Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Generate test report
        run: mvn surefire-report:report

      - name: List target directory
        run: ls -R target/reports

      - name: Upload test 
        uses: actions/upload-artifact@v4.
        with:
          name: test-reports
          path: ci-cd/recipe-planner-fronend-and-backend/recipe-planner-backend/target/surefire-reports